// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Parking_Api.Data;

#nullable disable

namespace Parking_Api.Migrations
{
    [DbContext(typeof(ContextDb))]
    [Migration("20260429054421_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Parking_Api.Models.Models+CarModel", b =>
                {
                    b.Property<int>("id_car")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_car"));

                    b.Property<string>("brand")
                        .HasColumnType("text");

                    b.Property<string>("color")
                        .HasColumnType("text");

                    b.Property<string>("license_plate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("model")
                        .HasColumnType("text");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("id_car");

                    b.HasIndex("user_id");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("Parking_Api.Models.Models+ParkingComplexModel", b =>
                {
                    b.Property<int>("id_complex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_complex"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("total_spots")
                        .HasColumnType("integer");

                    b.HasKey("id_complex");

                    b.ToTable("ParkingComplexes");
                });

            modelBuilder.Entity("Parking_Api.Models.Models+ParkingSessionModel", b =>
                {
                    b.Property<int>("id_session")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_session"));

                    b.Property<int>("car_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("entry_time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("exit_time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("parking_complex_id")
                        .HasColumnType("integer");

                    b.Property<int>("parking_spot_id")
                        .HasColumnType("integer");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("subscription_id")
                        .HasColumnType("integer");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("id_session");

                    b.HasIndex("car_id");

                    b.HasIndex("parking_complex_id");

                    b.HasIndex("parking_spot_id");

                    b.HasIndex("subscription_id");

                    b.HasIndex("user_id");

                    b.ToTable("ParkingSessions");
                });

            modelBuilder.Entity("Parking_Api.Models.Models+ParkingSpotModel", b =>
                {
                    b.Property<int>("id_spot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_spot"));

                    b.Property<string>("number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("parking_complex_id")
                        .HasColumnType("integer");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_spot");

                    b.HasIndex("parking_complex_id");

                    b.ToTable("ParkingSpots");
                });

            modelBuilder.Entity("Parking_Api.Models.Models+SubscriptionModel", b =>
                {
                    b.Property<int>("id_subscription")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_subscription"));

                    b.Property<DateOnly>("end_date")
                        .HasColumnType("date");

                    b.Property<DateOnly>("start_date")
                        .HasColumnType("date");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("subscription_plan_id")
                        .HasColumnType("integer");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("id_subscription");

                    b.HasIndex("subscription_plan_id");

                    b.HasIndex("user_id");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Parking_Api.Models.Models+SubscriptionPlanModel", b =>
                {
                    b.Property<int>("id_plan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_plan"));

                    b.Property<int>("duration_days")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("parking_complex_id")
                        .HasColumnType("integer");

                    b.Property<decimal>("price")
                        .HasColumnType("numeric");

                    b.HasKey("id_plan");

                    b.HasIndex("parking_complex_id");

                    b.ToTable("SubscriptionPlans");
                });

            modelBuilder.Entity("Parking_Api.Models.Models+UserModel", b =>
                {
                    b.Property<int>("id_user")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_user"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("role_id")
                        .HasColumnType("integer");

                    b.Property<string>("surname")
                        .HasColumnType("text");

                    b.HasKey("id_user");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Parking_Api.Models.Models+CarModel", b =>
                {
                    b.HasOne("Parking_Api.Models.Models+UserModel", "user")
                        .WithMany("cars")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("Parking_Api.Models.Models+ParkingSessionModel", b =>
                {
                    b.HasOne("Parking_Api.Models.Models+CarModel", "car")
                        .WithMany("parkingSessions")
                        .HasForeignKey("car_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parking_Api.Models.Models+ParkingComplexModel", "parkingComplex")
                        .WithMany("parkingSessions")
                        .HasForeignKey("parking_complex_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parking_Api.Models.Models+ParkingSpotModel", "parkingSpot")
                        .WithMany("parkingSessions")
                        .HasForeignKey("parking_spot_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parking_Api.Models.Models+SubscriptionModel", "subscription")
                        .WithMany("parkingSessions")
                        .HasForeignKey("subscription_id");

                    b.HasOne("Parking_Api.Models.Models+UserModel", "user")
                        .WithMany("parkingSessions")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("car");

                    b.Navigation("parkingComplex");

                    b.Navigation("parkingSpot");

                    b.Navigation("subscription");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Parking_Api.Models.Models+ParkingSpotModel", b =>
                {
                    b.HasOne("Parking_Api.Models.Models+ParkingComplexModel", "parkingComplex")
                        .WithMany("spots")
                        .HasForeignKey("parking_complex_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("parkingComplex");
                });

            modelBuilder.Entity("Parking_Api.Models.Models+SubscriptionModel", b =>
                {
                    b.HasOne("Parking_Api.Models.Models+SubscriptionPlanModel", "subscriptionPlan")
                        .WithMany("subscriptions")
                        .HasForeignKey("subscription_plan_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parking_Api.Models.Models+UserModel", "user")
                        .WithMany("subscriptions")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("subscriptionPlan");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Parking_Api.Models.Models+SubscriptionPlanModel", b =>
                {
                    b.HasOne("Parking_Api.Models.Models+ParkingComplexModel", "parkingComplex")
                        .WithMany("subscriptionPlans")
                        .HasForeignKey("parking_complex_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("parkingComplex");
                });

            modelBuilder.Entity("Parking_Api.Models.Models+CarModel", b =>
                {
                    b.Navigation("parkingSessions");
                });

            modelBuilder.Entity("Parking_Api.Models.Models+ParkingComplexModel", b =>
                {
                    b.Navigation("parkingSessions");

                    b.Navigation("spots");

                    b.Navigation("subscriptionPlans");
                });

            modelBuilder.Entity("Parking_Api.Models.Models+ParkingSpotModel", b =>
                {
                    b.Navigation("parkingSessions");
                });

            modelBuilder.Entity("Parking_Api.Models.Models+SubscriptionModel", b =>
                {
                    b.Navigation("parkingSessions");
                });

            modelBuilder.Entity("Parking_Api.Models.Models+SubscriptionPlanModel", b =>
                {
                    b.Navigation("subscriptions");
                });

            modelBuilder.Entity("Parking_Api.Models.Models+UserModel", b =>
                {
                    b.Navigation("cars");

                    b.Navigation("parkingSessions");

                    b.Navigation("subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
